Vidly/Vidly.Web/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Vidly.Web.Data;
using Vidly.Web.Models;
using Vidly.Web.ViewModels;

namespace Vidly.Web.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET : Customers
        public IActionResult Index()
        {

            return View();
        }

        // GET : Customers/Details/{id}
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var customer = await _context.Customers
                .Include(c => c.MembershipType)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (customer == null)
                return NotFound();


            return View(customer);
        }

        // GET : Customers/New
        public async Task<IActionResult> New()
        {
            var membershipTypes = await _context.MembershipTypes.ToListAsync();
            var viewModel = new CustomerViewModel
            {
                Customer = new Customer(),
                MembershipTypes = MembershipType.ConvertToSelectListItem(membershipTypes)
            };
            ViewData["Title"] = "Add new customer";

            return View("CustomerForm", viewModel);
        }

        // POST : Customers/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Id,Name,BirthDate,IsSubscribedToNewsletter,MembershipTypeId")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Customers.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var viewModel = new CustomerViewModel
            {
                Customer = customer,
                MembershipTypes = MembershipType.ConvertToSelectListItem(await _context.MembershipTypes.ToListAsync())
            };
            ViewData["Title"] = "Add new customer";

            return View("CustomerForm", viewModel);
        }

        // GET : Customers/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var customer = await _context.Customers.SingleAsync(c => c.Id == id);
            if (customer == null)
                return NotFound();

            var membershipTypes = await _context.MembershipTypes.ToListAsync();
            var viewModel = new CustomerViewModel
            {
                Customer = customer,
                MembershipTypes = MembershipType.ConvertToSelectListItem(membershipTypes)
            };

            ViewData["Title"] = "Edit customer";

            return View("CustomerForm", viewModel);
        }

        //POST : Customers/Save/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(int id, [Bind("Id,Name,BirthDate,IsSubscribedToNewsletter,MembershipTypeId")] Customer customer)
        {
            if (id != customer.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var viewModel = new CustomerViewModel
            {
                Customer = customer,
                MembershipTypes = MembershipType.ConvertToSelectListItem(await _context.MembershipTypes.ToListAsync())
            };
            ViewData["Title"] = "Edit customer";
            return View("CustomerForm", viewModel);
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

Vidly/Vidly.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using Vidly.Web.Data;
using Vidly.Web.Models;
using Vidly.Web.ViewModels;

namespace Vidly.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET : Movies
        public IActionResult Index()
        {
            if (User.IsInRole("CanManageMovies"))
                return View();

            return View("ReadonlyIndex");
        }

        // GET : Movies/Details/{id}
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var movie = await _context.Movies.Include(m => m.Genre).SingleAsync(m => m.Id == id);
            if (movie == null)
                return NotFound();

            return View(movie);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        // GET : Movies/New
        public async Task<IActionResult> New()
        {
            var genres = await _context.Genres.ToListAsync();
            var viewModel = new MovieViewModel
            {
                Movie = new Movie(),
                Genres = Genre.ConverToSelectListItem(genres)
            };
            ViewData["Title"] = "Add new movie";

            return View("MovieForm", viewModel);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        // POST : Movies/Add
        [HttpPost]
        public async Task<IActionResult> Add([Bind("Id,Name,GenreId,ReleasedDate,NumberInStock")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                movie.AddedDate = DateTime.Now;
                movie.NumberAvailable = movie.NumberInStock;
                _context.Movies.Add(movie);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            var viewModel = new MovieViewModel
            {
                Movie = new Movie(),
                Genres = Genre.ConverToSelectListItem(await _context.Genres.ToListAsync())
            };
            ViewData["Title"] = "Add new movie";

            return View("MovieForm", viewModel);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        // GET : Movies/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var movie = await _context.Movies.SingleAsync(m => m.Id == id);
            if (movie == null)
                return NotFound();

            var viewModel = new MovieViewModel
            {
                Movie = movie,
                Genres = Genre.ConverToSelectListItem(await _context.Genres.ToListAsync())
            };
            ViewData["Title"] = "Edit Movie";

            return View("MovieForm", viewModel);
        }

        [Authorize(Roles = RoleName.CanManageMovies)]
        // POST : Movies/Save
        [HttpPost]
        public async Task<IActionResult> Save(int id, [Bind("Id,Name,GenreId,ReleasedDate,NumberInStock")] Movie movie)
        {
            if (id != movie.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var movieInDb = _context.Movies.Single(m => m.Id == movie.Id);

                    // Using _context.Update() will bind more fields from viewmodel
                    movieInDb.Name = movie.Name;
                    movieInDb.GenreId = movie.GenreId;
                    movieInDb.ReleasedDate = movie.ReleasedDate;
                    movieInDb.NumberInStock = movie.NumberInStock;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var viewModel = new MovieViewModel
            {
                Movie = movie,
                Genres = Genre.ConverToSelectListItem(await _context.Genres.ToListAsync())
            };
            ViewData["Title"] = "Edit Movie";

            return View("CustomerForm", viewModel);
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(m => m.Id == id);
        }
    }
}

Vidly/Vidly.Web/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Vidly.Web.Controllers
{
    public class RentalsController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

Vidly/Vidly.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/datatables/DataTables-1.10.22/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/datatables/datatables.css" rel="stylesheet" />
    <link href="~/css/typeahead.css" rel="stylesheet" />
    <link href="~/toastr.js/toastr.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vidly</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="New">New Rental</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Vidly - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/lib/datatables/DataTables-1.10.22/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/datatables.js"></script>
    <script src="~/typeahead.js/typeahead.bundle.js"></script>
    <script src="~/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>